# Generated by Django 3.2 on 2021-04-22 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import homework.services


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='New HomeWork', max_length=255, verbose_name='HomeWork Title')),
                ('description', models.CharField(max_length=255, verbose_name='Homework description')),
            ],
        ),
        migrations.CreateModel(
            name='HomeWorkResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_answer', models.FileField(upload_to=homework.services.get_file_path, verbose_name='Upload file')),
                ('note', models.CharField(max_length=255, verbose_name='Homework note')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='The Homework completed')),
                ('mark', models.PositiveSmallIntegerField(default=0, verbose_name='Mark')),
                ('status', models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('declined', 'declined'), ('finished', 'finished')], default='pending', max_length=20, verbose_name='Status')),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='homeworkresult', to='homework.homework')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeworkresult', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'HomeWorkResult',
                'verbose_name_plural': 'HomeWorkResults',
            },
        ),
    ]
